"""add_llm_usage_task_records_analysis_tables

Revision ID: 6a479e00e916
Revises: e555af71c41a
Create Date: 2026-08-08 08:11:23.489178
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '6a479e00e916'
down_revision: Union[str, None] = 'e555af71c41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
   op.create_table('analysis_reports',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=False),
   sa.Column('stock_code', sa.String(length=16), nullable=False),
   sa.Column('stock_name', sa.String(length=64), nullable=False),
   sa.Column('rating', sa.String(length=16), nullable=False),
   sa.Column('confidence', sa.Float(), nullable=False),
   sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_analysis_reports_stock_code'), 'analysis_reports', ['stock_code'], unique=False)
   op.create_index(op.f('ix_analysis_reports_user_id'), 'analysis_reports', ['user_id'], unique=False)
   op.create_table('llm_usage',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=False),
   sa.Column('module', sa.String(length=64), nullable=False),
   sa.Column('model', sa.String(length=64), nullable=False),
   sa.Column('prompt_tokens', sa.Integer(), nullable=False),
   sa.Column('completion_tokens', sa.Integer(), nullable=False),
   sa.Column('cost_fen', sa.Integer(), nullable=False),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_llm_usage_user_id'), 'llm_usage', ['user_id'], unique=False)
   op.create_table('task_records',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('task_type', sa.String(length=64), nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=True),
   sa.Column('ref_id', sa.Integer(), nullable=True),
   sa.Column('status', sa.String(length=16), nullable=False),
   sa.Column('progress', sa.Integer(), nullable=False),
   sa.Column('error', sa.Text(), nullable=True),
   sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
   sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
   sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_task_records_task_type'), 'task_records', ['task_type'], unique=False)
   op.create_index(op.f('ix_task_records_user_id'), 'task_records', ['user_id'], unique=False)
   # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
   op.drop_index(op.f('ix_task_records_user_id'), table_name='task_records')
   op.drop_index(op.f('ix_task_records_task_type'), table_name='task_records')
   op.drop_table('task_records')
   op.drop_index(op.f('ix_llm_usage_user_id'), table_name='llm_usage')
   op.drop_table('llm_usage')
   op.drop_index(op.f('ix_analysis_reports_user_id'), table_name='analysis_reports')
   op.drop_index(op.f('ix_analysis_reports_stock_code'), table_name='analysis_reports')
   op.drop_table('analysis_reports')
   # ### end Alembic commands ###
