"""monitor notification config_id nullable for system alerts

Revision ID: 8ea157a2625d
Revises: db8cf092d4d2
Create Date: 2026-08-08 15:47:50.659206
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

 

revision: str = '8ea157a2625d'
down_revision: Union[str, None] = 'db8cf092d4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
 # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitor_notifications', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
 # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitor_notifications', 'config_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
