"""add m5 news and us research tables

Revision ID: db8cf092d4d2
Revises: eaa98711eb2a
Create Date: 2026-08-08 15:46:31.524394
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

 

revision: str = 'db8cf092d4d2'
down_revision: Union[str, None] = 'eaa98711eb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
 # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('url_hash', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('industries', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_items_source'), 'news_items', ['source'], unique=False)
    op.create_index(op.f('ix_news_items_url_hash'), 'news_items', ['url_hash'], unique=True)
    op.create_table('us_research_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('data_status', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_us_research_reports_trade_date'), 'us_research_reports', ['trade_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
 # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_us_research_reports_trade_date'), table_name='us_research_reports')
    op.drop_table('us_research_reports')
    op.drop_index(op.f('ix_news_items_url_hash'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_source'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
