"""add_m4_portfolio_monitor_risk_tables

Revision ID: eaa98711eb2a
Revises: eeadc87c2c8c
Create Date: 2026-08-08 14:15:29.701094
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'eaa98711eb2a'
down_revision: Union[str, None] = 'eeadc87c2c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
   op.create_table('monitor_configs',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=False),
   sa.Column('stock_code', sa.String(length=16), nullable=False),
   sa.Column('stock_name', sa.String(length=64), nullable=False),
   sa.Column('entry_price', sa.Float(), nullable=False),
   sa.Column('target_price', sa.Float(), nullable=False),
   sa.Column('stop_price', sa.Float(), nullable=False),
   sa.Column('profit_pct', sa.Float(), nullable=False),
   sa.Column('loss_pct', sa.Float(), nullable=False),
   sa.Column('interval_min', sa.Integer(), nullable=False),
   sa.Column('channels', sa.String(length=128), nullable=False),
   sa.Column('ai_enabled', sa.Boolean(), nullable=False),
   sa.Column('status', sa.String(length=16), nullable=False),
   sa.Column('last_checked_at', sa.String(length=32), nullable=True),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_monitor_configs_stock_code'), 'monitor_configs', ['stock_code'], unique=False)
   op.create_index(op.f('ix_monitor_configs_user_id'), 'monitor_configs', ['user_id'], unique=False)
   op.create_table('portfolio_reports',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=False),
   sa.Column('health_score', sa.Float(), nullable=False),
   sa.Column('diagnosis_json', sa.JSON(), nullable=True),
   sa.Column('task_id', sa.Integer(), nullable=True),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_portfolio_reports_user_id'), 'portfolio_reports', ['user_id'], unique=False)
   op.create_table('portfolio_stocks',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=False),
   sa.Column('stock_code', sa.String(length=16), nullable=False),
   sa.Column('stock_name', sa.String(length=64), nullable=False),
   sa.Column('shares', sa.Integer(), nullable=False),
   sa.Column('cost_price', sa.Float(), nullable=False),
   sa.Column('auto_monitor', sa.Boolean(), nullable=False),
   sa.Column('current_price', sa.Float(), nullable=False),
   sa.Column('market_value', sa.Float(), nullable=False),
   sa.Column('profit_loss', sa.Float(), nullable=False),
   sa.Column('profit_pct', sa.Float(), nullable=False),
   sa.Column('industry', sa.String(length=64), nullable=False),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_portfolio_stocks_stock_code'), 'portfolio_stocks', ['stock_code'], unique=False)
   op.create_index(op.f('ix_portfolio_stocks_user_id'), 'portfolio_stocks', ['user_id'], unique=False)
   op.create_table('risk_warnings',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=True),
   sa.Column('stock_code', sa.String(length=16), nullable=False),
   sa.Column('stock_name', sa.String(length=64), nullable=False),
   sa.Column('level', sa.String(length=16), nullable=False),
   sa.Column('category', sa.String(length=32), nullable=False),
   sa.Column('message', sa.String(length=256), nullable=False),
   sa.Column('value', sa.String(length=32), nullable=False),
   sa.Column('days', sa.Integer(), nullable=False),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_risk_warnings_stock_code'), 'risk_warnings', ['stock_code'], unique=False)
   op.create_index(op.f('ix_risk_warnings_user_id'), 'risk_warnings', ['user_id'], unique=False)
   op.create_table('monitor_notifications',
   sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
   sa.Column('config_id', sa.Integer(), nullable=False),
   sa.Column('user_id', sa.Integer(), nullable=False),
   sa.Column('stock_code', sa.String(length=16), nullable=False),
   sa.Column('stock_name', sa.String(length=64), nullable=False),
   sa.Column('ntype', sa.String(length=32), nullable=False),
   sa.Column('title', sa.String(length=128), nullable=False),
   sa.Column('content', sa.Text(), nullable=True),
   sa.Column('status', sa.String(length=16), nullable=False),
   sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
   sa.ForeignKeyConstraint(['config_id'], ['monitor_configs.id'], ),
   sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
   sa.PrimaryKeyConstraint('id')
   )
   op.create_index(op.f('ix_monitor_notifications_config_id'), 'monitor_notifications', ['config_id'], unique=False)
   op.create_index(op.f('ix_monitor_notifications_user_id'), 'monitor_notifications', ['user_id'], unique=False)
   # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
   op.drop_index(op.f('ix_monitor_notifications_user_id'), table_name='monitor_notifications')
   op.drop_index(op.f('ix_monitor_notifications_config_id'), table_name='monitor_notifications')
   op.drop_table('monitor_notifications')
   op.drop_index(op.f('ix_risk_warnings_user_id'), table_name='risk_warnings')
   op.drop_index(op.f('ix_risk_warnings_stock_code'), table_name='risk_warnings')
   op.drop_table('risk_warnings')
   op.drop_index(op.f('ix_portfolio_stocks_user_id'), table_name='portfolio_stocks')
   op.drop_index(op.f('ix_portfolio_stocks_stock_code'), table_name='portfolio_stocks')
   op.drop_table('portfolio_stocks')
   op.drop_index(op.f('ix_portfolio_reports_user_id'), table_name='portfolio_reports')
   op.drop_table('portfolio_reports')
   op.drop_index(op.f('ix_monitor_configs_user_id'), table_name='monitor_configs')
   op.drop_index(op.f('ix_monitor_configs_stock_code'), table_name='monitor_configs')
   op.drop_table('monitor_configs')
   # ### end Alembic commands ###
