"""add_m3_tables

Revision ID: eeadc87c2c8c
Revises: 6a479e00e916
Create Date: 2026-08-08 09:04:11.740331
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



revision: str = 'eeadc87c2c8c'
down_revision: Union[str, None] = '6a479e00e916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
  op.create_table('sector_reports',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('report_date', sa.String(length=16), nullable=False),
  sa.Column('bull_json', sa.JSON(), nullable=True),
  sa.Column('bear_json', sa.JSON(), nullable=True),
  sa.Column('neutral_json', sa.JSON(), nullable=True),
  sa.Column('rotation_json', sa.JSON(), nullable=True),
  sa.Column('summary_json', sa.JSON(), nullable=True),
  sa.Column('agents_json', sa.JSON(), nullable=True),
  sa.Column('task_id', sa.Integer(), nullable=True),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_sector_reports_report_date'), 'sector_reports', ['report_date'], unique=False)
  op.create_table('dragon_tiger_reports',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=True),
  sa.Column('period_days', sa.Integer(), nullable=False),
  sa.Column('stats_json', sa.JSON(), nullable=True),
  sa.Column('top_stocks_json', sa.JSON(), nullable=True),
  sa.Column('institutions_json', sa.JSON(), nullable=True),
  sa.Column('analysis_text', sa.Text(), nullable=True),
  sa.Column('task_id', sa.Integer(), nullable=True),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_dragon_tiger_reports_user_id'), 'dragon_tiger_reports', ['user_id'], unique=False)
  op.create_table('main_force_runs',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=True),
  sa.Column('run_date', sa.String(length=16), nullable=False),
  sa.Column('candidates_count', sa.Integer(), nullable=False),
  sa.Column('filtered_count', sa.Integer(), nullable=False),
  sa.Column('recommended_json', sa.JSON(), nullable=True),
  sa.Column('excluded_json', sa.JSON(), nullable=True),
  sa.Column('token_total', sa.Integer(), nullable=False),
  sa.Column('task_id', sa.Integer(), nullable=True),
  sa.Column('analysis_json', sa.JSON(), nullable=True),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_main_force_runs_run_date'), 'main_force_runs', ['run_date'], unique=False)
  op.create_index(op.f('ix_main_force_runs_user_id'), 'main_force_runs', ['user_id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_main_force_runs_user_id'), table_name='main_force_runs')
  op.drop_index(op.f('ix_main_force_runs_run_date'), table_name='main_force_runs')
  op.drop_table('main_force_runs')
  op.drop_index(op.f('ix_dragon_tiger_reports_user_id'), table_name='dragon_tiger_reports')
  op.drop_table('dragon_tiger_reports')
  op.drop_index(op.f('ix_sector_reports_report_date'), table_name='sector_reports')
  op.drop_table('sector_reports')
  # ### end Alembic commands ###
